# Generated by Django 4.1.3 on 2022-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='as', max_length=250),
            preserve_default=False,
        ),
    ]
