# Generated by Django 4.1.3 on 2022-11-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=6165),
            preserve_default=False,
        ),
    ]
