# Generated by Django 4.1.3 on 2022-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='branding',
            name='branding_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
