# Generated by Django 4.1.3 on 2022-11-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_tags_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_small',
        ),
    ]
